{% set name = "dagmc_h5m_file_inspector" %}

package:
  name: "{{ name|lower }}"
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python {{ python }}
    - setuptools
  run:
    - python
    - moab
    - numpy

test:
  imports:
    - dagmc_h5m_file_inspector
  requires:
    - pytest
  source_files:
    - tests/
    - dagmc_h5m_file_inspector/inspect-dagmc-h5m-file
  # TODO fix error of not finding output files
  # commands:
  #   - pytest tests
  commands:
      - pytest tests/test_python_api_usage.py


about:
  home: "https://github.com/fusion-energy/dagmc_h5m_file_inspector"
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://github.com/fusion-energy/dagmc_h5m_file_inspector
  dev_url: https://github.com/fusion-energy/dagmc_h5m_file_inspector
  summary: Extracts information from DAGMC h5m files including volumes number, material tags

extra:
  recipe-maintainers:
    - shimwell
