from importlib.metadata import version

__version__ = version("dagmc_h5m_file_inspector")

from .core import (
    BoundingBox,
    combine_h5m_files,
    convert_h5m_to_vtkhdf,
    get_bounding_box,
    get_materials,
    get_surface_area_by_cell_id,
    get_surface_area_by_material_name,
    get_surface_area_by_surface_id,
    get_surface_ids,
    get_surface_ids_by_cell_id,
    get_surface_ids_by_material_name,
    get_surface_shared_status,
    get_triangle_conn_and_coords_by_volume,
    get_volumes,
    get_volumes_and_materials,
    get_volumes_by_cell_id,
    get_volumes_by_cell_id_and_material_name,
    get_volumes_by_material_name,
    move,
    remove_materials,
    rotate_around_axis,
    set_openmc_material_volumes,
)

__all__ = [
    "BoundingBox",
    "combine_h5m_files",
    "convert_h5m_to_vtkhdf",
    "get_bounding_box",
    "get_materials",
    "get_surface_area_by_cell_id",
    "get_surface_area_by_material_name",
    "get_surface_area_by_surface_id",
    "get_surface_ids",
    "get_surface_ids_by_cell_id",
    "get_surface_ids_by_material_name",
    "get_surface_shared_status",
    "get_triangle_conn_and_coords_by_volume",
    "get_volumes",
    "get_volumes_and_materials",
    "get_volumes_by_cell_id",
    "get_volumes_by_cell_id_and_material_name",
    "get_volumes_by_material_name",
    "move",
    "remove_materials",
    "rotate_around_axis",
    "set_openmc_material_volumes",
]
